preload = /home/dev/Wallpaper-Bank/wallpapers/Space-Nebula.png

wallpaper = eDP-1,/home/dev/Wallpaper-Bank/wallpapers/Space-Nebula.png
wallpaper = HDMI-A-1,/home/dev/Wallpaper-Bank/wallpapers/Space-Nebula.png
